version: '2.1'
orbs:
  snyk: snyk/snyk@1.1.2
jobs:
  build:
    docker:
      - image: 'cimg/node:lts'
    steps:
      - checkout
      - run: npm ci
      - run: sudo npm i -g snyk-delta
      - snyk/scan:
          fail-on-issues: false
          additional-arguments: --json --print-deps > snyk-output.json
      - run: cat output snyk-output.json | snyk-delta --baselineOrg $SNYK_ORG --baselineProject $SNYK_PROJECT
workflows: null