name: Example workflow for Node using Snyk
on: push
jobs:
  sca:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: false
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN_COLLABORATOR }}
        with:
          command: test
          args: --severity-threshold=high
